### ISSUE TITLE
Unable to Set Up Repo - anujsgithub

### ISSUE THREAD

**Issue by anujsgithub** [uwhpsc-2016/homework1#11]
Chris:

I am facing the same issues while accessing the private Repo.

Anuj

**Comment by quantheory** [comment]
Does this link work for you?

https://github.com/uwhpsc-2016/homework1-anujsgithub

**Comment by anujsgithub** [comment]
No I see an error page 404
[cid:image001.png@01D1900B.FF592F90]

Anuj

**Comment by quantheory** [comment]
OK. I think that @cswiercz needs to change permissions on the repo.

**Comment by cswiercz** [comment]
@anujsgithub Try navigating here now: https://github.com/uwhpsc-2016/homework1-anujsgithub Let me know if this works.

@quantheory @mvelegar I just made both of you admins on the UWHPSC org so that you two have access to these collaborator settings I mentioned in [this comment](https://github.com/uwhpsc-2016/homework1/issues/10#issuecomment-206524255)

**Comment by anujsgithub** [comment]
This works! Thanks..Anuj

**Comment by quantheory** [comment]
Good to hear.
